services:
  radarr:
    image: linuxserver/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Hong_Kong
    volumes:
      - ~/docker/config_files/radarr/config:/config
      - /mnt:/mnt
    ports:
      - "7878:7878"
    restart: unless-stopped
    networks:
      - proxy

networks:
  proxy:
    external: true
