services:
  pulsarr:
    image: lakker/pulsarr:latest
    container_name: pulsarr
    ports:
      - "3003:3003"
    volumes:
      - ~/docker/config_files/pulsarr/data:/app/data
      - .env:/app/.env
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - proxy

networks:
  proxy:
    external: true